### ISSUE TITLE
Upgrade to angular version 17

### ISSUE THREAD

**Issue by vzdendyak** [pm20390/ng-google-tag-manager#1]
Hi team, do you have plans to update this library to be compatible with the Angular V17?

Thanks in advance!

**Comment by pm20390** [comment]
Hi! This fork was merged back in to the initial repository. I had this fork for before the changes were able to be incorporated.

Here's the link to the other repo: https://github.com/mzuccaroli/angular-google-tag-manager

It would be good to open the issue over there.
